name: testBuilding

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 19
    - name: Test npm run build
      run: |
        npm install
        npm run build
        npm run build:release
